### ISSUE TITLE
Create simple test infrastructure

### ISSUE THREAD

**Issue by rtisma** [icgc-argo/song-qc-sidecar#4]
The goal is to create an easy way for the qc module to be tested with minimal coding.

One way to do this, is create 2 directories:
- passing
- failing

the `passing` directory should contain passing payloads. When these payloads are run against the handler, assert there are no errors

the `failing` directory should contain payloads that are invalidated by the qc module. When these payloads are run against the handler, assert errors of the expected type are thrown.

tests should be written using pytest

**Comment by KevinFHartmann** [comment]
Completed as part of #1.
